### ISSUE TITLE
is ready for production and where the documentation？

### ISSUE THREAD

**Issue by ruifly2012** [topfreegames/libpitaya#1]

**Comment by leohahn** [comment]
The lib is already being used in production. The API however is still quite unstable, so the documentation is still being worked on.

**Comment by arden** [comment]
is ready for production now?

**Comment by felipejfc** [comment]
it is, we are already using it in production games, documentation however is still pending @guthyerrz @leohahn

**Comment by leohahn** [comment]
We will work on improving the documentation

**Comment by fanhaipeng0403** [comment]
Has any progress?

**Comment by fanhaipeng0403** [comment]
Has any progress?
