### ISSUE TITLE
How does android client listen for messages broadcast from the server? 

### ISSUE THREAD

**Issue by arden** [topfreegames/libpitaya#10]
How does android client listen for messages broadcast from the server? 
I didn't find any relevant code in the c code.
Is there have a good example of android? We are now working on this framework.

**Comment by leohahn** [comment]
Currently we do not have official Java bindings for Android. The code at the `java` folder is deprecated and we do not currently use it. In order for it to work on android, you have to either use it within a C++ program and cross-compile it to android, or you have to create a Java binding for it and use the binding to run in android.

We currently use Unity to run on Android and iOS, and therefore this is our main binding that runs on both platforms. If you are not using Unity but native Java (or Kotlin), you have to create a binding for it. Here you can find more information on how to do that: https://developer.android.com/studio/projects/add-native-code.html

We want however to eventually have Java bindings, but at the moment we are not working on it.

**Comment by leohahn** [comment]
If you want to run c++or c on android, you can use the following function to listen for server pushes:
```
void pc_client_set_push_handler(pc_client_t *client, pc_push_handler_cb_t cb);
```

**Comment by arden** [comment]
I've compiled the android-related interface files using javacpp.

https://github.com/bytedeco/javacpp

**Comment by arden** [comment]
For the dynamic library generation on the android platform, I fork a code and then made changes.

https://github.com/taledog/libpitaya

**Comment by felipejfc** [comment]
hi @arden, good job on using javacpp to generate the JNI code for android, we will adopt your idea (thanks for that) and integrate it in our repo with the correct paths soon.

I think I can close this issue now, best!
