### ISSUE TITLE
support swift language?

### ISSUE THREAD

**Issue by arden** [topfreegames/libpitaya#5]
We are using swift language now, and we are currently investigating whether this development framework supports Swift well?

**Comment by leohahn** [comment]
Hi, we have not used Swift with libpitaya yet. However since the library is written in C, you can call it directly with Objective-C. In that case you can use a C FFI for Swift (it it has one) or call Objective-C directly. 

A PR here would be very appreciated! :)

**Comment by felipejfc** [comment]
I see that you managed to get it working by yourself in your fork @arden, nice!
Would you mind sending a PR with the swift example with the same structure / README style of the obj-c one?

thanks
