### ISSUE TITLE
have a full ios project example?

### ISSUE THREAD

**Issue by arden** [topfreegames/libpitaya#6]
I've created an ios project, and import the "_builds/ios/libpitaya-ios.a"，"libz.a, libuv_a.a" to project，But not to found "libssl.a and libcrypto.a".

When i'm build the project, that can't find "pitaya.h, pc_pitaya_i.h" in the code.

**Comment by guthyerrz** [comment]
The ios project was updated with some example test cases and a [README.md](https://github.com/topfreegames/libpitaya/blob/master/ios/PitayaClient/README.md) file to explain some functionalities
