### ISSUE TITLE
How does the ios client listen for messages broadcast from the server?

### ISSUE THREAD

**Issue by arden** [topfreegames/libpitaya#8]
How does the ios client listen for messages broadcast from the server? I can't find a way to do this in c code.

**Comment by guthyerrz** [comment]
Just added this to the [README](https://github.com/topfreegames/libpitaya/blob/master/ios/PitayaClient/README.md) and you can see a live example of this running in the tests cases found [here](https://github.com/topfreegames/libpitaya/blob/master/ios/PitayaClient/PitayaClientTests/PitayaClientTests.m)
