### ISSUE TITLE
CMake was unable to find a build program corresponding to "Ninja".  

### ISSUE THREAD

**Issue by arden** [topfreegames/libpitaya#9]
I was compiling the android client library on MacOS with the following errors, but I had ninja installed.

make setup-mac
make build-android

```
CMake Error at /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/CMakeDetermineSystem.cmake:100 (message):
  Could not find toolchain file:
  ../temp/android-ndk-r17b/build/cmake/android.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)


CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
make: *** [build-android] Error 1
```

**Comment by leohahn** [comment]
Did you run `brew install ninja`? If that does not work, you can modify the Makefile and remove the `-GNinja` section from the command. It will then use make instead of ninja.

**Comment by leohahn** [comment]
Oops, now that I saw, `setup-mac` should install ninja. Do you have brew installed? If it does not work just do what I mentioned in the comment above

**Comment by arden** [comment]
yes, I installed ninja with run " brew install ninja ". now, remove the -GNinja, but still reporting this error。

**Comment by arden** [comment]
ardendeiMac:libpitaya arden$ ninja
ninja: error: loading 'build.ninja': No such file or directory
ardendeiMac:libpitaya arden$

**Comment by leohahn** [comment]
Ok, now the error is related to the toolchain. It says that there is not a file `android.toolchain.cmake` in that path. This means you have to point the program to the NDK location you have. Suppose you downloaded and installed the NDK r17b at `~`. You would then run the following command to build for android:
```
make ANDROID_TOOLCHAIN_FILE=~/android-ndk-r17b/build/cmake/android.toolchain.cmake build-android
```
You can also run the target `setup-android-mac`, it will download the ndk into the folder `temp` at the current directory. If you do that, then you will have to change the ANDROID_TOOLCHAIN_FILE variable from the previous command to the newly downloaded ndk into the temp folder.

**Comment by leohahn** [comment]
A complete setup to build for android could be someting like the following:
```
make setup-android-mac
make ANDROID_TOOLCHAIN_FILE=temp/android-ndk-r17b/build/cmake/android.toolchain.cmake build-android
```

**Comment by leohahn** [comment]
Looking at the readme now this is an issue on the makefile, I will update it with the correct instructions for android.

**Comment by arden** [comment]
```
make setup-android-mac
make ANDROID_TOOLCHAIN_FILE=temp/android-ndk-r17b/build/cmake/android.toolchain.cmake build-android
```
it's ok.
